### ISSUE TITLE
Monochrome Toolbar Icon

### ISSUE THREAD

**Issue by dustigroove** [claudiodangelis/google-keep-as-popup#13]
This is a very handy extension, thank you for making it. That said; would it be possible to use, or offer the option to use (ie: Pushbullet, LastPass), a monochrome icon? I find that many extensions either come with or offer a monochrome option as they tend to distract and clash much less with the website content.
![chrome_toolbar](https://cloud.githubusercontent.com/assets/3325820/12362402/21336a58-bb91-11e5-912f-cdf1fc5743ba.png)

**Comment by claudiodangelis** [comment]
Hello, thanks for your suggestion, I will include a monochrome icon in the upcoming release which should be available in a week or two.

**Comment by dustigroove** [comment]
That is excellent, thank you!

**Comment by claudiodangelis** [comment]
:)
I'm keeping this issue open until the feature is implemented.

**Comment by claudiodangelis** [comment]
@dustigroove, I added a monochrome icon as per version 0.5.2.
Thanks again!

![xy4b](https://cloud.githubusercontent.com/assets/941963/12705094/5ae16cba-c86a-11e5-94a5-13d241320e76.png)

**Comment by dustigroove** [comment]
Looks great, thanks so much!
